require('./bootstrap')
window.$ = require('jquery/dist/jquery.min')
window.Turbolinks = require('turbolinks')
require('livewire-turbolinks/dist/livewire-turbolinks')
require('jquery-ui-dist/jquery-ui.min')
require('./script')
